### ISSUE TITLE
suggestion: run

### ISSUE THREAD

**Issue by gurgeous** [piotrmurach/tty#23]
It would be great if TTY supported running external commands. Example API below. Note that commands will be echoed if verbose is true.

```ruby
attr_accessor :verbose

# run a command and echo output, raise an exception if it fails
def run(command, args = nil)
# run a command and return output, raise an exception if it fails
def run_capture(command, args = nil)
# run a command and suppress output, raise an exception if it fails
def run_quietly(command, args = nil)

# returns true if the command fails
def run_fails?(command, args = nil)
# returns true if the command succeeds
def run_succeeds?(command, args = nil)
```

**Comment by peter-murach** [comment]
I'm not sure how much more these commands would provide above the built-in ruby helpers for running external commands like `system` etc... ?

**Comment by gurgeous** [comment]
Several advantages:

- A uniform way to handle exit codes. Commands that file should throw an exception.
- Echoing commands. This is quite useful for install/setup scripts. Example: a setup script that runs apt-get install. It's nice to have output that can be copied and pasted into the command line, but this is tricky without proper escaping.
- I suspect that many script writers don't really understand when to use backticks vs. system() vs. popen. It's nice to have documented wrappers with a uniform api.

**Comment by peter-murach** [comment]
The advantages convince me that this is quite useful addition. Please bear with me on this and all the other propositions. I have a list of few other libraries that I'm wanting to write as part of `tty`. I will consider how things you have put forward mesh with what I'm trying to do. I will soon start/release a new project based on one of your suggestions so that we can start collaboration and take things from there. Does that sound like a plan?

**Comment by gurgeous** [comment]
Sure, no worries. I have a bit of time to pitch in if you can give me some pointers. I'm happy to do the whole thing, including tests... Just let me know how you'd like to proceed.

**Comment by piotrmurach** [comment]
Hi Adam, to deliver on the promise, I've created [tty-command](https://github.com/piotrmurach/tty-command). The api boils down to `execute` and `execute!` methods, all the other things such as capturing output are implemented. I hope you like it. Please let me have your thoughts/code/PRs. The library is not released yet as I wanted to have your contributions first.

I'm going to close this issue so that any future discussion can carry on tty-command issue tracker. There are few things to finish before release which I'm going to include in the issues list.
