### ISSUE TITLE
Updated Release?

### ISSUE THREAD

**Issue by colstrom** [piotrmurach/tty#29]
The dependencies were updated recently (thanks!). Is there a new release being pushed to RubyGems anytime soon?

Looking forward to it!

**Comment by piotrmurach** [comment]
The dependencies are still being updated as we speak. Since there are new releases of`pastel` and `tty-prompt` I need to bring few other dependencies in line such as `tty-file` and `tty-command` as otherwise there would be conflicts. I'm aware that I haven't published a new version of `tty` for quite a long time and actually been working on releasing new version. I didn't deem it crucial as people could always install gems individually.

I haven't announced it but I've also redesigned and updated the [site](http://piotrmurach.github.io/tty/) to go with new release. Please bear with me and I will have something ready pretty soon and you will be the first to know! For the future I plan to make a release each month.

**Comment by colstrom** [comment]
That makes a lot of sense, and I appreciate the quick response.

**Comment by piotrmurach** [comment]
New version `0.6.0` release! As an extra, if you fancy seeing details about loaded plugins call `TTY.plugins`. Enjoy!

**Comment by colstrom** [comment]
Awesome. I'll give it a spin and let you know if I hit any snags.

Thanks!
