### ISSUE TITLE
Overwrite executable warning when trying to install gem

### ISSUE THREAD

**Issue by lacostenycoder** [piotrmurach/tty#56]
#11 # Describe the problem
Overwrite executable warning

### Steps to reproduce the problem
```
gem install tty-reader
# or 
gem install tty-prompt
```

### Actual behaviour
I get this warning in the terminal
```
wisper's executable "console" conflicts with countries
Overwrite the executable? [yN]

# for gem install tty-prompt
Fetching: necromancer-0.5.1.gem (100%)
Successfully installed necromancer-0.5.1
Fetching: equatable-0.6.1.gem (100%)
Successfully installed equatable-0.6.1
Fetching: tty-color-0.5.0.gem (100%)
Successfully installed tty-color-0.5.0
Fetching: pastel-0.7.3.gem (100%)
Successfully installed pastel-0.7.3
wisper's executable "console" conflicts with countries
Overwrite the executable? [yN]  ERROR:  Error installing tty-prompt:
	"console" from wisper conflicts with installed executable from countries
```
I tried to find out what whisper even is and only found 
https://rubygems.org/gems/whisper with no link to any viewable source code or documentation.  So what does this even do?

### Expected behaviour
Provide information of why I'm overwriting an executable, and what the dependency is even doing. 

### Describe your environment

* OS version: MacOS Mojave 10.14.3 (18D109 
* Ruby version: ruby 2.4.1p111
* TTY version: none, afraid to install until this is resolved.

**Comment by piotrmurach** [comment]
Hi Lance,

Thanks for using `tty` gem!

This issue is not related to `tty` and it also isn't related to `wisper` dependency(btw. the name is wipser and not whisper - https://rubygems.org/gems/wisper). The `wisper` installation made the error manifests itself but wasn't the reason. 

As I searched, I found that the issue is with `countries` gem, which makes files in `bin` executable. The `countries` gem should probably conflict with other gems much earlier. Here is the [issue](https://github.com/hexorx/countries/pull/571) as reported in the `countries` gem repository. So you need to upgrade your `countries` gem version and that should remove your problem.
